### ISSUE TITLE
Buffer Queue Limit Size 

### ISSUE THREAD

**Issue by McRobie** [logzio/logzio-k8s#14]
Cluster:
AWS EKS

Description:
Fluentd pods unable to ship to logzio because of BufferQueueLimitError
related https://github.com/kubernetes/kubernetes/issues/19405

`[warn]: emit transaction failed: error_class=Fluent::BufferQueueLimitError error="queue size exceeds limit" tag="kubernetes.var.log.containers*`

Workaround:
Because we've deployed fluentd as a daemonset, we restart the pod experiencing this issue.

**Comment by idohalevi** [comment]
@McRobie 
Thank you for the comment. 
Not sure what is the workaround you found for it. Can you describe how you solved it?

**Comment by idohalevi** [comment]
@McRobie 
A good explanation from one of kubernetes members:

`Fluent::BufferQueueLimitError` is an OK thing, it happens if the buffer overflows. Fluentd then retries to send logs, so just that doesn't indicate that logs are lost.

The question is what got buffer to overflow in the first place. There are two options:

Logz.io endpoint doesn't work/not accessible. You can check it by sending requests to the Logz.io service manually.

You send too many logs. In this case, increase the number of threads that send logs and the size of the queue. Don't forget to adjust resources on the DaemonSet according.

What other errors/warn do you see that can help debug it?

**Comment by McRobie** [comment]
Hi Idohalevi, thank you for responding. I've not seen a pod experiencing this issue emit other warnings or errors. I've also not seen it recover, so I delete the pod and then the daemonset will launch a new one. The only change I've made so far is to increase the memory request to "300Mi" but unfortunately have still encountered this error. We have approximately 90 pods running and usually only 2 or three every 12 hours have this issue. Would you suggest increasing threads & buffer queue limit?

**Comment by idohalevi** [comment]
@McRobie 
Yes, please try it out.
